# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='top_addons_count',
            field=models.IntegerField(default=0),
        ),
    ]
