# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_parser', '0003_vendor_top_addons_total_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='top_addons_count',
            new_name='top_addons_sum',
        ),
    ]
