# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_parser', '0004_auto_20170624_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='top_addons_total_sum',
            new_name='top_addons_total_download_sum',
        ),
    ]
